### ISSUE TITLE
CH VACD Recommendation Immunization Recommendations Section Profile (François von Kaenel, BFH)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#13]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-recommendation-section-immunization-recommendations.html

Wrong binding "Immunization Target Disease Codes" for vaccinationCode is  (the same as for targetDisease ?!)

François von Kaenel, BFH

**Comment by ralych** [comment]
Jupp, das ist wohl falsch. Sollte wohl das gleiche sein wie bei Immunization.

**Comment by eHealth-Suisse** [comment]
Binding has been changed, okay. Other issues with value set are targeted in other issues.
François will be informed by email since I don't know his github account.
