### ISSUE TITLE
Recommendation-Categories for Immunizations (François von Kaenel, BFH)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#14]
ch.fhir.ig.ch-vacd#0.1.0 /ValueSet-ch-vacd-recommendation-categories-vs.html

Missing translations fr, it, en

François von Kaenel, BFH

**Comment by ralych** [comment]
http://art-decor.org/decor/services/RetrieveValueSet?id=2.16.756.5.30.1.127.11.4&effectiveDate=2017-06-12T14:21:51&prefix=cdachvacd-&version=2017-06-13T08:48:50&format=xml&language=en-US&ui=en-US

**Comment by eHealth-Suisse** [comment]
translations added for Swiss official languages Fr and It.
Romansh translation not delivered, at least in a first phase, exchange format value sets will not be translated into Romansh.
English translation still missing, will be accessible by start of ballot, current state here: https://github.com/ehealthsuisse/ch-vacd/blob/master/doc/VS_Translations_eImpfungen_Stand_20210615.xlsx
ticket issuer @vnf1 for information and potential objections
