### ISSUE TITLE
Incomplete ValueSet Allergies for eVACDOC (Daniel Ratschiller, CISTEC AG)

### ISSUE THREAD

**Issue by drats-cis** [ehealthsuisse/ch-vacd#15]
The value set seems to us to be too short. 

From the current mapping work on the IG Allergy&Intolerances, we would know that the following allergies from the HCI-Hospindex would exist in the minium.

CHA-Code | Auslösende Substanz im Hospindex | ISCODE (X=aktiv) | Anzahl Produkte bei HCI | Titel der Allergie (Hospindex) | Code1 Cistec-Mapping | Text1 Cistec-Mapping
-- | -- | -- | -- | -- | -- | --
CHA-387 | (null) | X | #NV | Cholera-Impfstoff-Allergie |   |  
CHA-395 | (null) | X | #NV | Haemophilus influenza   B-Impfstoff-Allergie | 294664000 | Allergy to   Haemophilus influenzae type b vaccine (finding)
CHA-390 | Hepatitis-A-Adsorbat-Impfstoff | X | 4 | Hepatitis A-Impfstoff-Allergie | 294663006 | Allergy to   Hepatitis A virus vaccine (finding)
CHA-389 | Hepatitis-B-Impfstoff, rekombiniert,   monovalent | X | 8 | Hepatitis B-Impfstoff-Allergie | 294646007 | Allergy to   Hepatitis B virus vaccine (finding)
CHA-394 | Pertussis acellulär Adsorbat   Impfstoff | X | 3 | Pertussis-Impfstoff-Allergie | 294651001 | Allergy to   pertussis vaccine (finding)
CHA-484 | Pneumokokken-Polysaccharid-CRM-Konjugat-Impfstoff,   13-valent, Pneumokokken-Polysaccharid-Impfstoff 23-valent | X | 2 | Pneumokokken-Impfstoff-Allergie | 294652008 | Allergy to   pneumococcal vaccine (finding)
CHA-392 | Poliomyelitis-Impfstoff inaktiviert,   trivalent, Poliomyelitisviren Typ 1 inaktiviert (Mahoney), Poliomyelitisviren   Typ 2 inaktiviert (MEF-1), Poliomyelitisviren Typ 3 inaktiviert (Saukett) | X | 19 | Poliomyelitis-Impfstoff-Allergie | 294654009 | Allergy to   Poliovirus vaccine (finding)
CHA-124 | Rota Virus   human (Stamm: RIX4414) | X | 1 | Rotavirus-Lebendimpfstoff-Allergie | 700468006 | Allergy to   Rotavirus vaccine (finding)
CHA-388 | Röteln-Lebend-Impfstoff (HDC-Zellen),   Stamm Wistar RA 27/3 | X | 5 | Röteln-Impfstoff-Allergie | 294656006 | Allergy to   rubella vaccine (finding)
CHA-486 | Tetanus-Adsorbat-Impfstoff | X | 8 | Tetanus-Impfstoff-Allergie | 294658007 | Allergy to   tetanus vaccine (finding)
CHA-391 | Tollwut-Impfstoff, inaktiviert   (HDC-Zellen); Stamm WISTAR PM/WI 38-1503-3M, Tollwut-Impfstoff, inaktiviert   (PCEC); Stamm Flury LEP | X | 4 | Tollwut-Impfstoff-Allergie | 294655005 | Allergy to   Rabies vaccine (finding)
CHA-396 | BCG-Lebend-Impfstoff; Stamm RIVM,   BCG-Lebend-Impfstoff; Stamm TICE, Mycobacterium bovis BCG (Stamm-Kopenhagen   1331) | X | 4 | Tuberkulose-Impfstoff-Allergie | 293635003 | Allergy to tuberculin (finding)
CHA-393 | Salmonella typhi, lebend; Stamm Ty   21a, Typhus-Lebend-Impfstoff, oral, Typhus-Polysaccharid-Impfstoff | X | 3 | Typhus-Impfstoff-Allergie | 294659004 | Allergy to   component of vaccine product containing Salmonella enterica subspecies   enterica serovar Typhi antigen
CHA-397 | Varizellen-Lebend-Impfstoff   attenuiert (Stamm OKA), Varizellen-Lebend-Impfstoff; Stamm OKA/Merck | X | 6 | Varizellen-Impfstoff-Allergie | 294639003 | Allergy to   Varicella-zoster virus antibody (finding)

Inspired by SCT, there could be as many as 19:
https://browser.ihtsdotools.org/?perspective=full&conceptId1=863903001&edition=MAIN/2021-01-31&release=&languages=en
•	      Allergy to component of vaccine product containing Bacillus anthracis antigen (finding)
•	      Allergy to component of vaccine product containing Bordetella pertussis antigen (finding)
•	      Allergy to component of vaccine product containing Clostridium tetani antigen (finding)
•	      Allergy to component of vaccine product containing Corynebacterium diphtheriae antigen (finding)
•	      Allergy to component of vaccine product containing Haemophilus influenzae type B antigen (finding)
•	      Allergy to component of vaccine product containing Hepatitis A virus antigen (finding)
•	      Allergy to component of vaccine product containing Hepatitis B virus antigen (finding)
•	      Allergy to component of vaccine product containing Human poliovirus antigen (finding)
•	      Allergy to component of vaccine product containing Influenza virus antigen (finding)
•	      Allergy to component of vaccine product containing Mumps orthorubulavirus antigen (finding)
•	      Allergy to component of vaccine product containing Neisseria meningitidis antigen (finding)
•	      Allergy to component of vaccine product containing only Clostridium tetani and Corynebacterium diphtheriae antigens (finding)
•	      Allergy to component of vaccine product containing only Measles morbillivirus and Mumps orthorubulavirus and Rubella virus antigens (finding)
•	      Allergy to component of vaccine product containing Rabies lyssavirus antigen (finding)
•	      Allergy to component of vaccine product containing Rotavirus antigen (finding)
•	      Allergy to component of vaccine product containing Rubella virus antigen (finding)
•	      Allergy to component of vaccine product containing Salmonella enterica subspecies enterica serovar Typhi antigen (finding)
•	      Allergy to component of vaccine product containing Streptococcus pneumoniae antigen (finding)
•	      Allergy to component of vaccine product containing Vaccinia virus antigen (finding)

What do you think, shouldn't the valueset be extended accordingly?

**Comment by ralych** [comment]
The allergies relevant for immunizations are based on the EKIF recommendations and the CDSS system of viavac.

**Comment by drats-cis** [comment]
I am slightly puzzled by the wontfix label. What kind of CDS is it if it does not take into account a known allergy to a vaccine for vaccination recommendations?

**Comment by eHealth-Suisse** [comment]
duplicate with #57  or which ticket?
maybe worth to ask back to EKIF why/if these allergies are not relevant

**Comment by ralych** [comment]
Additional to EKIF the valueset is taken over from the [art-decor valueset](https://art-decor.org/art-decor/decor-valuesets--cdachvacd-). The work wat was to be done is to translate CDA to FHIR.

**Comment by eHealth-Suisse** [comment]
value set has been enlarged, issue closed.
Ticketsteller @drats-cis  zur Kenntnis und für allfällige Einwände.
