### ISSUE TITLE
Incomplete Valueset Illnesses undergone for immunization (Daniel Ratschiller, CISTEC AG)

### ISSUE THREAD

**Issue by drats-cis** [ehealthsuisse/ch-vacd#16]
We wonder how complete this value list is:
http://build.fhir.org/ig/ehealthsuisse/ch-vacd/ValueSet-ch-vacd-illnesses-undergone-for-immunizaion-vs.html

Vaccines were/are on the CH market for the following diseases. Should they not also be included?:

- Cholera
- Haemophilus influenza B
- Pertussis
- Pneumococcus
- Poliomyelitis
- Rotavirus
- Rabies
- Tuberculosis
- Typhoid fever
- Varicella
- COVID-19!

And 16901001 Central European encephalitis (disorder) should be translated as FSME (Frühsommer-Meningoenzephalitis), as all translations D, F, I are still pending.

**Comment by ralych** [comment]
Value set is transformed from art-decor which is defined for the CDA.

**Comment by eHealth-Suisse** [comment]
I included the "question" label again since it seems that the value sets need review/validation from experts

**Comment by eHealth-Suisse** [comment]
list was enlarged and translations delivered, http://build.fhir.org/ig/ehealthsuisse/ch-vacd/ValueSet-ch-vacd-targetdiseasesandillnessesundergoneforimmunization-vs.html
ticket issuer @drats-cis for information and potential objection
