### ISSUE TITLE
Allergies for eVACDOC (François von Kaenel, BFH)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#17]
ch.fhir.ig.ch-vacd#0.1.0 /ValueSet-ch-vacd-allergies-immunizations-vs.html

The list is very short, this is probably on work. Or does a "complete" list already exist?

François von Kaenel, BFH

**Comment by ralych** [comment]
see #50 and #57

**Comment by eHealth-Suisse** [comment]
and see #15 for yet another duplicate . will be worked on on issue #57

**Comment by eHealth-Suisse** [comment]
duplicate of #15, #17, #57, can be closed accordingly. Value Set has been enlarged, see http://build.fhir.org/ig/ehealthsuisse/ch-vacd/ValueSet-ch-vacd-immunization-allergyintolerances-vs.html 
@vnf1  zur Kenntnis und für allfällige Einwände.
