### ISSUE TITLE
Illnesses undergone for immunization (François von Kaenel, BFH)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#18]
ch.fhir.ig.ch-vacd#0.1.0 /ValueSet-ch-vacd-illnesses-undergone-for-immunizaion-vs.html

Translations are missing and list of illnesses incomplete

François von Kaenel, BFH

**Comment by ralych** [comment]
Value set is transformed from art-decor which is defined for the CDA.

**Comment by ralych** [comment]
see #16
