### ISSUE TITLE
SwissRisksForImmunizations (François von Kaenel, BFH)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#19]
ch.fhir.ig.ch-vacd#0.1.0 /ValueSet-ch-vacd-risks-vs.html

Translations missing

François von Kaenel, BFH

**Comment by ralych** [comment]
see #52

**Comment by eHealth-Suisse** [comment]
translations added, http://build.fhir.org/ig/ehealthsuisse/ch-vacd/ValueSet-ch-vacd-risks-vs.html
only English display missing, will remain unchanged; see for reasoning #52 
ticket issuer @vnf1 for information and potential objections
