### ISSUE TITLE
Immunization Administration (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#20]
ch.fhir.ig.ch-vacd#0.1.0 /immunization-administration.html

Die Seiten "http://fhir.ch/ig/ch-vacd/immunization-administration.html" und "http://fhir.ch/ig/ch-vacd/immunization-certificate.html" sind ausser den Wörter "Administration" und "Certificate" identisch. 
Empfehlung: Einen Abschnitt zur Beschreibung der Unterschiede einfügen.

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
see also in the section 
#23 
#24

**Comment by eHealth-Suisse** [comment]
Beschreibungen ergänzt, Ticket wird geschlossen.
Ticketsteller @emmanueleschmann zur Kenntnis und für allfällige Einwände.
