### ISSUE TITLE
5 Immunization Recommendation Response - JSON Representation (François von Kaenel, BFH)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#22]
ch.fhir.ig.ch-vacd#0.1.0 /Bundle-5-ImmunizationRecommendationResponse.json.html

The "5 Immunization Recommendation Response - JSON Representation" example does not contain the section "otherrelevantobservations" (LOINC 30954-2), on the other hand it contains the section "sectionImmunizationRecomendations1" (LOINC 18776-5 Plan of care), that is not specified in the profile.

Is there any mismatch here?

François von Kaenel, BFH

**Comment by ralych** [comment]
in the example both sections are here and also defined in the profile.

**Comment by eHealth-Suisse** [comment]
ticket issuer @vnf1 for information and potential objections
