### ISSUE TITLE
CH VACD Immunization Administration Composition Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#23]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-composition-immunization-administration.html

Die Profile «CH VACD Immunization Certificate Composition Profile» und «CH VACD Immunization Certificate Composition Profile» scheinen sich nur bzgl. der Erläuterung zum Element Composition.title zu unterscheiden.
Empfehlung:
Falls kein weiterer Unterschied zwischen beiden Profilen: Beide Profile zur Unterstützung der Wartbarkeit der FHIR.ch – Profile zu einem einzigen Profil zusammenführen.
Falls doch relevante Unterschiede zwischen beiden Profilen bestehen: Einen Abschnitt «Boundaries and Relationships» ergänzen, der den Unterschied zwischen beiden Profilen klar beschreibt und deren Anwendungsfälle auflistet.

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
Was ist hier gemeint?
«CH VACD Immunization Certificate Composition Profile» und «CH VACD Immunization Certificate Composition Profile»
ist das gleiche?
identische frage in #24

**Comment by ralych** [comment]
see #20

**Comment by eHealth-Suisse** [comment]
Beschreibungen ergänzt, Ticket wird geschlossen.
Ticketsteller @emmanueleschmann zur Kenntnis und für allfällige Einwände.
