### ISSUE TITLE
CH VACD Immunization Certificate Composition Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#24]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-composition-immunization-certificate.html

Die Profile «CH VACD Immunization Certificate Composition Profile» und «CH VACD Immunization Certificate Composition Profile» scheinen sich nur bzgl. der Erläuterung zum Element Composition.title zu unterscheiden.
Empfehlung:
Falls kein weiterer Unterschied zwischen beiden Profilen: Beide Profile zur Unterstützung der Wartbarkeit der FHIR.ch – Profile zu einem einzigen Profil zusammenführen.
Falls doch relevante Unterschiede zwischen beiden Profilen bestehen: Einen Abschnitt «Boundaries and Relationships» ergänzen, der den Unterschied zwischen beiden Profilen klar beschreibt und deren Anwendungsfälle auflistet.

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
Was ist hier gemeint?
«CH VACD Immunization Certificate Composition Profile» und «CH VACD Immunization Certificate Composition Profile»
ist das gleiche?

**Comment by ralych** [comment]
see #20
