### ISSUE TITLE
Profiles (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#26]
ch.fhir.ig.ch-vacd#0.1.0 /profiles.html

Diverse Verweise aus den hier aufgelisteten Profilen auf die CH-Core-EPR-Profile stützen die Annahme, dass einige dieser Profilel ausschliesslich für den Austausch mit dem elektronischen Patientdossier (EPR) zu verwenden ist (wie z.Bsp. dass die Composition von CHCoreCompositionEPR abgeleitet ist oder auch die Vorgabe, dass die subject-Unterelemente ein CH Core Composition Patient Profile EPR referenzieren).
Empfehlung: Dies in der Profilbeschreibung klar beschreiben, z.Bsp. in Analogie zu CH-EMED mit «… defines the documents for the exchange of immunization information in the context of the EPR (electronic patient record) in Switzerland» 

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
Gemäss auftrag war es eVACD in FHIR überzuführen und in anlehnung an ch-emed.
Der Punkt ist berechtigt, da das auch ausserhalb des EPR gebraucht werden soll und darf.

**Comment by eHealth-Suisse** [comment]
actually it is the same question as already posed in issue #8
