### ISSUE TITLE
CH VACD Immunization Certificate Document Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#27]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-document-immunization-certificate.html

Diverse Verweise aus den Profilen auf die CH-Core-EPR-Profile stützen die Annahme, dass dieses Profil ausschliesslich für den Austausch mit dem elektronischen Patientdossier (EPR) zu verwenden ist (wie z.Bsp. dass die Composition von CHCoreCompositionEPR abgeleitet ist oder auch die Vorgabe, dass die subject-Unterelemente ein CH Core Composition Patient Profile EPR referenzieren).
Empfehlung: Dies in der Profilbeschreibung klar beschreiben, z.Bsp. in Analogie zu CH-EMED mit «… defines the documents for the exchange of immunization information in the context of the EPR (electronic patient record) in Switzerland» (sowohl in der Übersicht http://fhir.ch/ig/ch-vacd/profiles.html sowie auf der Profilseite selbst)

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
see #28
