### ISSUE TITLE
1 Immunization Administration - JSON Representation (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#29]
ch.fhir.ig.ch-vacd#0.1.0 /Bundle-1-ImmunizationAdministration.json.html

falsche Sprachangaben: entry[0]. "language": "en-US", aber die sprachbezogenen Inhalte der untergeordneten Elemente sind dennoch nicht in Englisch sonsdern in deutscher Sprache gehalten, z.Bsp.: entry[0].section[0].title: "Liste der verabreichten Impfungen".
Empfehlung: Alle Beispiele von VACD nach widersprüchlichen Sprachangaben durchsuchen und korrigieren.

Emmanuel Eschmann, CISTEC AG

**Comment by eHealth-Suisse** [comment]
wurde etwas geändert? ist immer noch drin wie von emmanuel beschrieben, vgl. http://build.fhir.org/ig/ehealthsuisse/ch-vacd/Bundle-1-1-ImmunizationAdministration.json.html oder http://build.fhir.org/ig/ehealthsuisse/ch-vacd/Composition-2-1-ImmunizationAdministrationComposition.json.html

**Comment by ralych** [comment]
beispiele neu generiert mit korrektur der sprache. sind ein paar dinge untergegangen. sollte nun komplett sein, mit ausnahme der namen

**Comment by eHealth-Suisse** [comment]
ticketsteller @emmanueleschmann zur info und für allfällige einwände
