### ISSUE TITLE
CH VACD Immunization Recommendation Request Document Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#31]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-document-immunization-recommendation-request.html

Dieses Profil dient der Zusammenstellung von Daten für eine Clinical Decision Support Anfrage und nicht zum Datenaustausch mit dem elektronischen Patientendossier. Weshalb ist der für das Request Dokument verwendete Bundle dennoch vom Type «CHCoreDocumentEPR», welches für den Datenaustausch mit dem elektronischen Patientendossier definiert wurde?

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
see #32

**Comment by eHealth-Suisse** [comment]
es ist auf jeden fall für response auch zutreffend, oder? kannst du das dort ändern, auch im falle dass es kein ticket dazu gibt?
