### ISSUE TITLE
CH VACD Immunization Recommendation Request Document Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#32]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-document-immunization-recommendation-request.html

Dieses Profil dient der Zusammenstellung von Daten für die Antwort eines Clinical Decision Support Systems und nicht zum Datenaustausch mit dem elektronischen Patientendossier. Weshalb ist der für das Response Dokument verwendete Bundle dennoch vom Type «CHCoreDocumentEPR», welches für den Datenaustausch mit dem elektronischen Patientendossier definiert wurde?

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
Dies ist korrekt und kann gewechselt werden.

**Comment by eHealth-Suisse** [comment]
Erledigt.
Ticketsteller @EmmanuelEschmann zur Kenntnis und für allfällige Einwände.
