### ISSUE TITLE
Overloaded Valueset RouteOfAdministration (Immunization) (Daniel Ratschiller, CISTEC AG)

### ISSUE THREAD

**Issue by drats-cis** [ehealthsuisse/ch-vacd#33]
http://build.fhir.org/ig/ehealthsuisse/ch-vacd/ValueSet-ch-vacd-route-of-administration-vs.html

The present list comprises an absurd amount of 388 entries for ROAs. In the HCI Hospindex there are 2 valuesets on the subject, which are already target-oriented for practice with 82 entries and according to EDQM with 55 entries.

Wouldn't it be desirable to use EDQM codes for the EDQM-ROA value set as in the CH-EMED profile? Has 80 entries.
http://build.fhir.org/ig/ehealthsuisse/ch-emed/ValueSet-edqm-routeofadministration.html 

What do the prefix underline, i.e. _ values in the list mean, they seem to cause some redundancies. See attached Excel with an attempt to normalise and compare to ROA valuesets from Hospindex: [ROA_VACD.xlsx](https://github.com/ehealthsuisse/ch-vacd/files/6143463/ROA_VACD.xlsx)

**Comment by drats-cis** [comment]
Ok, I now understand that there are problems in this valueset with a hierarchically structured trunk.
The huge list here:
http://build.fhir.org/ig/ehealthsuisse/ch-vacd/ValueSet-ch-vacd-route-of-administration-vs.html
comes from here:
https://terminology.hl7.org/2.0.0/CodeSystem-v3-RouteOfAdministration.html
Question: Can't this be solved more elegantly in FHIR-Modelling?

**Comment by ralych** [comment]
Was transformed from art-decor. see [ref](https://art-decor.org/art-decor/decor-valuesets--cdachvacd-?id=2.16.756.5.30.1.1.11.78&effectiveDate=2018-04-19T00:00:00)

**Comment by eHealth-Suisse** [comment]
once again the "question" label because it need advice / validation from an expert

**Comment by ralych** [comment]
VS IPS as EDQM base with translated values from the VS defined in the FHIR profile.
this will result in a set of EDQM codes for immunization use.

**Comment by eHealth-Suisse** [comment]
only a subset of 7 terms out of the EDQM ROA terms where chosen: codes which will be needed for use case administration, http://build.fhir.org/ig/ehealthsuisse/ch-vacd/ValueSet-ch-vacd-route-of-administration-vs.html
ticket issuer @drats-cis for information and potential objection
