### ISSUE TITLE
CH VACD Immunization Section Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#35]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-section-immunization.html

Dieses Profil referenziert an verschiedenen Stellen FHIR-Ressourcen wie Encounter oder Location statt die in FHIR.ch definierten Profile.
Korrektur: Überarbeitung mit Referenzierung der vorhandenen FHIR.ch – Profile

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
see #37

**Comment by eHealth-Suisse** [comment]
duplikat von #37 , wird entsprechend geschlossen
