### ISSUE TITLE
CH VACD Medical Problems Section Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#37]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-section-medical-problems.html

Dieses Profil referenziert an verschiedenen Stellen FHIR-Ressourcen wie Encounter auf statt die in FHIR.ch definierten Profile zu verwenden.
Korrektur: Überarbeitung mit Referenzierung der vorhandenen FHIR.ch – Profile
PS: Dies gilt in Analogie für alle anderen VACD-Profile, die FHIR-Ressourcen wie Patient, MedicationAdministration, MedicationDispense, MedicationStatement, MedicationRequest, Practitioner, PractitionerRole oder Organization, für die wir bereits FHIR - CH - Profile haben. -> Bitte alle anderen VACD-Profile diesbezüglich prüfen und korrigiren.

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
Das ist zu diskutieren, ob alle Referenzen immer zwingend auf CH-Core Profile verweisen müssen?
FHIR WG Diskussion

**Comment by eHealth-Suisse** [comment]
wie in FHIR WG diskutiert umgesetzt, ticket wird geschlossen
ticketsteller @emmanueleschmann zur kenntnis und für allfällige einwände
