### ISSUE TITLE
CH VACD Recommendation Past Illness Section Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#43]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-recommendation-section-pastillnesses.html

Dieses Profil wurde abgeleitet von der Ressource «Observation»
Korrektur: Die FHIR Ressource «Condition» wäre wohl die korrekterweise zur verwendende Ressource.

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
see #40

**Comment by eHealth-Suisse** [comment]
Geht jetzt auf Condition zurück (via CHVACDCondition), Ticket wird geschlossen.
Ticketsteller @EmmanuelEschmann zur Kenntnis und für allfällige Einwände.
