### ISSUE TITLE
CH VACD Recommendation Pregnancy Section Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#44]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-recommendation-section-pregnancy.html

Dieses Profil wurde abgeleitet von der Ressource «Observation»
Korrektur: Die FHIR Ressource «Condition» wäre wohl die korrekterweise zur verwendende Ressource.

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
see #41

**Comment by eHealth-Suisse** [comment]
Geht jetzt auf Condition zurück (via CHVACDREcommendatonCondition), Ticket wird geschlossen.
Ticketsteller @EmmanuelEschmann zur Kenntnis und für allfällige Einwände.
