### ISSUE TITLE
CH VACD Recommendations Allergies Section Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#45]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-recommendation-section-allergies.html

Dieses Profil wurde abgeleitet von der Ressource «Observation»
Korrektur: Die FHIR Ressource «AllergyIntolerance» wäre wohl die korrekterweise zur verwendende Ressource.

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
see #4

**Comment by eHealth-Suisse** [comment]
Ticket #4 geschlossen, entsprechend dieses Duplikat auch.
