### ISSUE TITLE
CH VACD Observation Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#46]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-section-observation.html

Abschnitt «Boundaries and Relationships» ergänzen, welches die genaue Abgrenzung zum Profil «CH VACD Other Relevant Observations Section» beschreibt

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
see #47

**Comment by eHealth-Suisse** [comment]
duplikat von #47, entsprechend auch geschlossen
