### ISSUE TITLE
CH VACD Other Relevant Observations Section (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#47]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-section-other-observations.html

Abschnitt «Boundaries and Relationships» ergänzen, welches die genaue Abgrenzung zum Profil «CH VACD Observation Profile» beschreibt.

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
"Relevant Observation Section" ist die  Definition für die "Other Relevant Observations" und leitet vom CH VACD Observation Profile ab.
Beschreibung kann präzisiert werden.

**Comment by eHealth-Suisse** [comment]
wurde ergänzt, ticket geschlossen
Ticketsteller @emmanueleschmann zur Kenntnis und für allfällige Einwände.
