### ISSUE TITLE
CH VACD Recommendation Patient Profile (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#49]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-recommendation-patient.html

Dieses Profil wurde mit dem Ziel erstellt, die Angaben zum Patienten zu pseudonymisieren. Typischerweise gehören die Entfernung oder zumindest Verschleierung des lokalen Patienten-Identifiers, seines Geburtsdatums (-> z.Bsp. nur Angabe Alter zum Zeitpunkt des Recommendation Response) und des Wohnortes (PLZ ist bei kleinen Orten zu präzis -> typischerweise ersetzt durch Charakteristika der Wohngegend) dazu. Diese 3 Element sind jedoch Teil des CH VACD Recommendation Patient Profile.
Empfehlung: Ersatz dieser 3 Elemente durch pseudonymisierte Inhalte (denn in der Tat sind viele der die Response begleitenden Inhalte sehr heikel).

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
Es  handelt sich hier nicht um Anonymisierung sondern Pseudonymisierung.
Die Elemente sind abgesprochen mit dem CDSS.
Der lokale Identifier dient dazu den response entsprechend wieder zuordnen zu können. Alle anderen Identifier sollten nicht mehr zugelassen sein, da sonst Rückschlüsse gezogen werden können.

**Comment by eHealth-Suisse** [comment]
Plus: PLZ noch immer nötig für FSME-Empfehlung (könnte man zwar auf Kantonsebene heben)

**Comment by eHealth-Suisse** [comment]
Besprechung 28.4., Konsultation von früheren Unterlagen, Entscheid:
Kommentar von Roeland vom 17. März ist zutreffend, Angaben sind notwendig, wird so belassen.
Schliesse das Ticket mit Information an Ticketsteller.

**Comment by eHealth-Suisse** [comment]
Kommentar von Ticketsteller @EmmanuelEschmann. "vielen Dank für Deine Rückmeldung (… auch wenn es meiner Meinung nach weiterhin datenschutzmässig sehr heikel ist, dem CDSS (unnötigerweise!) das tagesgenaue Geburtsdatum und die PLZ des Patienten samt einer Vielzahl klinischer Daten zu schicken ….)."
