### ISSUE TITLE
Artifacts Summary - Additional Examples (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#5]
ch.fhir.ig.ch-vacd#0.1.0 /artifacts.html

In addition to the document examples it would be helpful for implementers to have examples for each defined profile (see also warnings in qa.html for the different profiles: The Implementation Guide contains no explicitly linked examples for this profile)

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
is it intended that for /scratch/ig-build-temp-R16G2E/repo/input/resources/structuredefinition/ch-vacd-condition.xml there is no example? otherwise thanks for all the added examples!

**Comment by ralych** [comment]
das ch-vacd-condition ist ein "abstraktes" von dem die anderen "conditions" (pregnancy, past-illness, medical problems,other relevand obs) ableiten, oder sollte man das so nicht machen?

**Comment by oliveregger** [comment]
doch kein Problem. Vielleicht die Warnung bei ignorewarnings.txt hinzufügen, dann weiss ein nächster Reviewer dass es explizit ist.
