### ISSUE TITLE
Allergies for eVACDOC (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#50]
ch.fhir.ig.ch-vacd#0.1.0 /ValueSet-ch-vacd-allergies-immunizations-vs.html

Prüft das Clinical Decision Support System tatsächlich nur auf Allergien auf Ei-Proteine und auf atopischer Dermatitis? Es existieren doch sehr viel weitere und spezifischere Allergien gegen Impfstoffe (auch wenn die Code-Liste extensible ist, so sollte sie dennoch möglichst spezifische Angaben definieren).

Emmanuel Eschmann, CISTEC AG

**Comment by ralych** [comment]
Es sind nur die Drug Intolerance (Atopic dermatitis) und die Food Intolerance (Egg Protein) relevant für die Impfempfehlung (EKIF)
Fix muss gemacht werden bezogen auf die Darstellung #57

**Comment by eHealth-Suisse** [comment]
Value Set wurde ergänzt, http://build.fhir.org/ig/ehealthsuisse/ch-vacd/ValueSet-ch-vacd-immunization-allergyintolerances-vs.html
Ticketsteller @emmanueleschmann zur Kenntnis und für allfällige Einwände.
