### ISSUE TITLE
align with international works on immunization certificates (annatina foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#53]
ch.fhir.ig.ch-vacd#0.1.0 /

check the currents works going on on the national and international level

annatina foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment]
documentation of Swiss Covid Certificate: https://github.com/admin-ch/CovidCertificate-Documents

**Comment by eHealth-Suisse** [comment]
work was done as far as possible and is integrated into current version.
will remain an issue for ongoing work; close this issue nevertheless because done for this release.
