### ISSUE TITLE
Immunization Target Disease Codes (annatina foppa, ehealth suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#54]
ch.fhir.ig.ch-vacd#0.1.0 /ValueSet-ch-vacd-diseases-vs.html

Several issues with this value set: 
> the display name is not correct (should be the one from SNOMED CT)
> some codes are inactive, should not be uses (e.g. varicella vaccination)
> typhus ->> I think actually meant is "typhoid vaccination"? (same mistake was on art-decor value set)
> it's similar, but not identical to http://ehealthsuisse.art-decor.org/cdachvacd-html-20200813T090711/voc-2.16.756.5.30.1.1.11.71-2020-06-26T000000.html ... why?
> repository for value sets should be art-decor

annatina foppa, ehealth suisse

**Comment by ralych** [comment]
The content is from the list out of the cdss (viavac/EKIF). The valueset in art decor is not complete.

**Comment by eHealth-Suisse** [comment]
see #6
