### ISSUE TITLE
SwissRisksForImmunizations (annatina foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#56]
ch.fhir.ig.ch-vacd#0.1.0 /ValueSet-ch-vacd-risks-vs.html

here (and to check with other value sets) the display name is german, shouldn't the basic language be English for all cases?

annatina foppa, eHealth Suisse

**Comment by ralych** [comment]
This code systems are transformed from art-decor

- [Swiss Complication Risks Code System](https://art-decor.org/art-decor/decor-valuesets--cdachvacd-?id=2.16.756.5.30.1.1.11.72&effectiveDate=)
- [Swiss Exposure Risks Code System](https://art-decor.org/art-decor/decor-valuesets--cdachvacd-?id=2.16.756.5.30.1.1.11.73&effectiveDate=2018-04-19T00:00:00)

**Comment by ralych** [comment]
see #52
