### ISSUE TITLE
Allergies for eVACDOC (Annatina, eHS (Besprechung mit roeland-juerg-pero))

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#57]
ch.fhir.ig.ch-vacd#0.1.0 /ValueSet-ch-vacd-allergies-immunizations-vs.html

link to type of allergy (food / drug allergy / intolerance)

Annatina, eHS (Besprechung mit roeland-juerg-pero)

**Comment by eHealth-Suisse** [comment]
see #15 for reasoning

**Comment by eHealth-Suisse** [comment]
@ralych hab nur noch einen einwand wegen der darstellung. Für Display würde ich den FSN von SNOMED CT nehmen und zuerst nur Code&FSN auführen; die Übersetzungen erst weiter unten als "additional language displays". vgl. vorgehen bei value sets: http://build.fhir.org/ig/ehealthsuisse/ch-emed/ValueSet-ActivePharmaceuticalIngredient.html und http://build.fhir.org/ig/ehealthsuisse/ch-emed/ValueSet-UnitCode.html

**Comment by ralych** [comment]
@eHealth-Suisse ich bin in der abklärung wie das zustande kommt. das kann aus erster sicht nicht gesteuert werden und wir so gebildet mit dem publisher.
habe im zulip mal einen [post](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Valueset.20Rendering/near/239707969) gemacht.

**Comment by ralych** [comment]
problem ist per builder oder profile oder weiss nicht was plötzlich gelöst

**Comment by eHealth-Suisse** [comment]
hauptsache gelöst :)
