### ISSUE TITLE
Orginal Representation: Kardinalität festlegen

### ISSUE THREAD

**Issue by annatinafoppa** [ehealthsuisse/ch-vacd#59]
bei Medication Card und eRezept ist die Mitlieferung eines PDFs mit den äquivalenten Informationen ein Muss -- bei welchen Impfdokumenten macht dies ebenfalls Sinn? -> am Mittwoch diskutieren

**Comment by ralych** [comment]
Ich denke das macht beim Immunization Certificate (Impfausweis) am meisten sinn.
ImmunizationAdministration ist für das austauschen einer/mehreren Impfungen.
VaccinationRecord ist sehr umfassend
Recommendation Request/Response ist auch eher technisch, bzw beim response wären die recommendations dargestellt am sinnvollsten. repräsentiert ja dann aber nicht den kompletten inhalt,

oder was wird gefordert bei der repräsentativen darstellung? der gesamte inhalt?

**Comment by eHealth-Suisse** [comment]
geht auf das Exchange Format Handbook zurück, Kapitel 9: https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/E/Exchange-format-handbook_part-1_v12.pdf
inhalt muss pro austauschformat festgelegt werde, der "relevante" Inhalt (PDF übernimmt quasi die Aufgabe des narrativen Teils).
für request/response eher nicht relevant, da ja nicht als Dok im EPD abgelegt

**Comment by eHealth-Suisse** [comment]
für Immunization Certificate ergänzt, ok
