### ISSUE TITLE
Immunization Target Disease Codes different between CDA and FHIR (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#6]
ch.fhir.ig.ch-vacd#0.1.0 /ValueSet-ch-vacd-diseases-vs.html

This ValueSet has different values then the corresponding CDA-CH VACD ValueSet https://art-decor.org/art-decor/decor-valuesets--cdachvacd-?id=2.16.756.5.30.1.1.11.71&effectiveDate=dynamic. The OID in the FHIR ValueSet does also not correspond to the FHIR ValiueSet 2.16.756.5.30.1.147.4.1.4.

If the CDA Format and FHIR Format should be equivalent, the same ValueSet should be used. In EMED all ValueSets are currently defined and managed in ART-DECOR and exported to the FHIR Implementation guide.

Oliver Egger, ahdis ag

**Comment by ralych** [comment]
This value set was not taken from the Art-Decor because incompletenes. The value set was taken from cdss viavac.

**Comment by eHealth-Suisse** [comment]
see also comments on #54 
which value set should be taken as a basis now, @ralych ? the one on art-decor or the one from FHIR/viavac?

**Comment by eHealth-Suisse** [comment]
only FHIR specification has been developed, no alignment with ArtDecor needed
VS: http://build.fhir.org/ig/ehealthsuisse/ch-vacd/ValueSet-ch-vacd-targetdiseasesandillnessesundergoneforimmunization-vs.html
Ticketissuer @oliveregger for information and potential objections
