### ISSUE TITLE
Profiles in IG

### ISSUE THREAD

**Issue by eHealth-Suisse** [ehealthsuisse/ch-vacd#61]
Analog wie heute für eMed besprochen auch für eVacd-Dokumente:
https://github.com/ehealthsuisse/ch-emed/issues/50 

- Profile Tab: show profile list (equivalent to ch-core)
- Profile according to documents -> move to document tabs

**Comment by ralych** [comment]
see [ci build](http://build.fhir.org/ig/ehealthsuisse/ch-vacd/)
