### ISSUE TITLE
Immunization Certificate - Missing Sections in Picture (Roeland Luykx (RALY))

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#66]
ch.fhir.ig.ch-vacd#1.0.0 /immunization-certificate-document.html

In the Picture of the Description, the additional sections - newly added - are missing.

Roeland Luykx (RALY)

**Comment by eHealth-Suisse** [comment]
thanks, although it will not last for long (see ticket about getting rid of document "certificate") ...
