### ISSUE TITLE
Immunization Certificate - image (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#67]
ch.fhir.ig.ch-vacd#1.0.0 /immunization-certificate-document.html

the image doesn't illustrate the additional profiles allergy & past illnesses which were added in the last ballot. has to be added

Annatina Foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment]
sorry, duplicate. will close it
