### ISSUE TITLE
additional sections for Immunization Administration document (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#68]
ch.fhir.ig.ch-vacd#1.0.0 /immunization-administration-document.html

In analogy to the Immunization Certificate, the Immunization Administration should also contain the additional sections on allergies and past-illnesses in order to remain a real subset of the Immunization Certificate and to make the assemblage of these documents in the EPR possible.
If added, please also replace the image of document

Annatina Foppa, eHealth Suisse

**Comment by annatinafoppa** [comment]
hello @ralych , sorry for the late replies -- could you add the according resource profiles also on the Immunization Administration document, paragraph 4.2 on http://build.fhir.org/ig/ehealthsuisse/ch-vacd/immunization-administration-document.html 
and, if possible, for user convenience to faster reach the single documents, add a dropdown list on the document tab as it is done on eMedication? http://build.fhir.org/ig/ehealthsuisse/ch-emed/index.html

**Comment by eHealth-Suisse** [comment]
ok
