### ISSUE TITLE
Swiss Medic Authorized Vaccines Codesystem - Cannonical Url and Translations (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#7]
ch.fhir.ig.ch-vacd#0.1.0 /CodeSystem-ch-vacd-swissmedic-cs.html

1. Kanonische URL: Ist die kanonische URL mit Swissmedic abgesprochen? Ansonsten eine kanonische URL dieses Implementation Guides verwenden
2. ValueSet ist noch nicht übersetzt (e.g. 417	Tollwut Impfstoff Mérieux	Tollwut Impfstoff Mérieux	Tollwut Impfstoff Mérieux	Tollwut Impfstoff Mérieux)

Oliver Egger, ahdis ag

**Comment by ralych** [comment]
url nicht mit swissmedic abgesprochen.

**Comment by eHealth-Suisse** [comment]
diskutieren, ob überhaupt mit swissmedic-codes gearbeitet werden soll

**Comment by eHealth-Suisse** [comment]
rather a question that needs clarification (e.g. by comparison with IPS) than a discussion point for the FHIR workgroup

**Comment by ralych** [comment]
wird nur noch eine auswahl sein. es werden für vaccineCode noch andere VS zugelassen.
