### ISSUE TITLE
Immunization Administration document (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#70]
ch.fhir.ig.ch-vacd#1.0.0 /immunization-administration-document.html

current descrption: "The Immunization Administration document describes the content and format of an Immunization Administration document containing exclusively the chapter with all applied immunizations and no further chapters." :

"all" is not correct
depending on outcome of issue #68, "no further chapters" has to be replaced as well

Annatina Foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment]
ok
