### ISSUE TITLE
Add ConceptMap's

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/ch-vacd#72]
Concept maps to be added:
- [SwissVaccines](http://fhir.ch/ig/ch-vacd/ValueSet/ch-vacd-vaccines-vs) -> [TargetDiseasesAndIllnessesUndergoneForImmunization](http://fhir.ch/ig/ch-vacd/ValueSet/ch-vacd-targetdiseasesandillnessesundergoneforimmunization-vs)
- [SwissVaccinationPlanImmunizations](http://fhir.ch/ig/ch-vacd/ValueSet/ch-vacd-ch-vaccination-plan-immunizations-vs) -> [TargetDiseasesAndIllnessesUndergoneForImmunization](http://fhir.ch/ig/ch-vacd/ValueSet/ch-vacd-targetdiseasesandillnessesundergoneforimmunization-vs)

**Comment by eHealth-Suisse** [comment]
thanks, will be reviewed by prof. siegrist
