### ISSUE TITLE
Complete TargetDisease VS

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/ch-vacd#73]
There are some diseases missing in the valueset in correspondance to the
- [SwissVaccinationPlanImmunizations](http://fhir.ch/ig/ch-vacd/ValueSet/ch-vacd-ch-vaccination-plan-immunizations-vs)
- [SwissVaccines](http://fhir.ch/ig/ch-vacd/ValueSet/ch-vacd-vaccines-vs)

**Comment by ralych** [comment]
consulting EKIF/BAG/viavac for the review

**Comment by eHealth-Suisse** [comment]
thanks, will be reviewed by prof. siegrist
