### ISSUE TITLE
Home - Reference to CDA-CH VACD (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#74]
ch.fhir.ig.ch-vacd#1.0.0 /

>This implemenation guide is based on the CDA-CH-VACD - Immunization Content 
>(eVACDOC) ART-DECOR® specification which has been published by eHealth Suisse.

Should this be rewritten to past tense? has been based out. In my understanding CDA-CH-VACD is now deprecated and the CH-VACD is not compatible to CDA-CH-VACD anymore, correct?

Oliver Egger, ahdis

**Comment by ralych** [comment]
Yes, the ch-vacd made a step forward to newer and perhaps correcter interpretation.
CDA-CH-VACD is not anymore in the "lead".

**Comment by eHealth-Suisse** [comment]
ok
