### ISSUE TITLE
References (to CH Core AND CH Core EPR?) (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#76]
ch.fhir.ig.ch-vacd#1.0.0 /StructureDefinition-ch-vacd-immunization.html

If I understand it correctly in the description of the documents, the documents can be used in the EPR context and also outside of it. Would it then perhaps make sense to set the references of the profiles (e.g. organization, practitioner, patient) to CH Core AND CH Core EPR?

Michaela Ziegler, ahdis ag

**Comment by ralych** [comment]
Generic documentation for CH IG's is still missing. Was discussed at FHIR WG.
@oliveregger what is the status

**Comment by ralych** [comment]
As discussed once in WG:
In EPR compositions for document bundles we use the EPR core profiles for practitioner, patient, organization.
In all other profiles which can be used as normal or in EPR we do reference to the CH core profiles.

**Comment by oliveregger** [comment]
thanks for the reminder, added https://github.com/hl7ch/ch-core/wiki/Guidelines-for-Swiss-IG-Developments that it should be now covered. feedback or discussion welcome

**Comment by ralych** [comment]
The references are defined according to the definition by the CH FHIR WG: See https://github.com/ehealthsuisse/ch-emed/issues/36#issuecomment-824019190 and https://github.com/hl7ch/ch-core/wiki
