### ISSUE TITLE
 Immunization Profile (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#8]
ch.fhir.ig.ch-vacd#0.1.0 /StructureDefinition-ch-vacd-section-immunization.html

1. Should identifier not be 1..[1 or *] to correspond to CDA representation?
2. patient, reference to CH Core Patient that it can be reused for non document exchange formats
3. practitioner, reference to CH Core PractitionerRole that Organization could also be provided
4. reasonCode: could it be skipped? what is the need for a fix coding? now no other coding for reasonCode could be added
5. protocolApplied, targetDisease: binding relax to extensible? if new targetDiseases would be introduced the profile could still be valid.

Oliver Egger, ahdis

**Comment by ralych** [comment]
1) has to be fixed
2/3) Diskussion in general to link to CH-Core and not to CH-Core-EPR profiles.
4) comes from CDA
5) has to be changed to extensible

**Comment by eHealth-Suisse** [comment]
tried to change the wrong enumartion on the reply, didn't succeed. 
point 2 -> 4; point 3 -> 5.
on point 4: is this requirement in CDA coming from a "higher source" or could it be changed there as well?

**Comment by ralych** [comment]
To point 3:
In my opinion, it should not be allowed to set an organization as performer on an immunization. it should be a practitioner as it is defined in CDA.

**Comment by ralych** [comment]
1. fixed
2. changed to non epr ch-core
3. changed to non epr ch-core
5. changed to extensible

Open question:
4. ArtDecor sagt: IMMUNIZ|2.16.840.1.113883.5.4|ActCode oder [<select>](http://art-decor.org/art-decor/decor-valuesets--cdachvacd-?id=2.16.756.5.30.1.1.11.69&effectiveDate=dynamic)|2.16.840.1.113883.6.96|SNOMED CT. Das habe ich nun als slicing drin und das valueset übernommen.

**Comment by ralych** [comment]
@eHealth-Suisse what means label change-resource here?

**Comment by annatinafoppa** [comment]
gemein war mit change-resource den wechsel auf ch-core, ist ja gemacht. die offene frage können wir morgen anschauen.

**Comment by ralych** [comment]
ReasonCode wird auf standard FHIR zurückgesetzt.
das richtige attribut ist [statusReason](http://hl7.org/fhir/R4/immunization-definitions.html#Immunization.statusReason ). Dabei sind die standardwerte korrekt.
