### ISSUE TITLE
Begriff "Certificate" hat Verwechslungspotential (Gabriel Hess, I4MI / BFH TI)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#80]
ch.fhir.ig.ch-vacd#1.0.0 /immunization-certificate-document.html

Der Name „Immunization Certificate“ für den Impfausweis als Auflistung der stattgehabten Impfungen finde ich etwas unglücklich, da im IT-Kontext ein Zertifikat eher etwas ist, das vom ausstellenden Akteur signiert wird. Und gerade im Impf-IT-Kontext gibt es dies mit dem COVID-Zertifikat neuerdings ja auch, weshalb „Immunization Certificate“ zu Verwechslungen führen könnte.

Dies deckt sich auch mit der Sprachregelung des BAG, das in der COVID-Kampagne hohen Wert darauf legt, dass unsignierte Dokumente eben keine „Impfausweise“ oder „Zertifikate“ sind (auch wenn auf dem „Impfausweis“ von 2019, der über die Bundespublikationen bestellt werden kann, auch noch der englische Begriff „Vaccination certificate“ drauf steht).

Alternative Begriffe wären: 
- Immunization card / Vaccination card
- Immunization booklet
- Immunization dossier

Gabriel Hess, I4MI / BFH TI

**Comment by ralych** [comment]
obsolete. Document definition is removed from IG

**Comment by eHealth-Suisse** [comment]
yes, obsolete, only two documents remaining:

- Impfdokumentation (Immunization Administration document)
- Impfdossier (Vaccination Record document)

issue creator @heg2 for information and potential objection
