### ISSUE TITLE
CH VACD Laboratory And Serology Profile, cardinality ofvalueQuantity  (Roeland Luykx, RALY GmbH)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#81]
ch.fhir.ig.ch-vacd#1.0.0 /StructureDefinition-ch-vacd-laboratory-serology.html

Restriction  valueQuantity 1..1 should be back to 0..1 and also valueCodeableConcept	 should be allowed.

Roeland Luykx (RALY GmbH)

**Comment by eHealth-Suisse** [comment]
ok
