### ISSUE TITLE
falscher eintrag bei rm für Windpocken ... Target disease and illnesses undergone for immunization (annatina foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#83]
ch.fhir.ig.ch-vacd#1.0.0 /ValueSet-ch-vacd-targetdiseasesandillnessesundergoneforimmunization-vs.html

code: 38907003 . Steht "STarrkrampf)" statt Windpocken, vermutlich Copy-Paste-Fehler.

annatina foppa, eHealth Suisse

**Comment by ralych** [comment]
duplicate to #78
