### ISSUE TITLE
Extension for Reference to Practitioner as Validator of Immunization entry (Roeland Luykx, RALY GmbH)

### ISSUE THREAD

**Issue by ralych** [ehealthsuisse/ch-vacd#87]

**Comment by ralych** [comment]
Will be resolved not via extension but by change of author.
Author == Patient means not validated
Author == Practitioner means validated

This will be done by a ImmunizationAdministration Document with "replaces" relation to the source document where a patient added the Immunization entry (Patient as Author)

--> Comment this in the profile and description page in IG

**Comment by eHealth-Suisse** [comment]
I agree with the text written, but why then is there still an extension on the IG? http://build.fhir.org/ig/ehealthsuisse/ch-vacd/StructureDefinition-ch-vacd-ext-immunization-recorder-reference.html should be done via XDS metadata

**Comment by ralych** [comment]
There is no author nor recorder reference property in the immunization resource. this is the reason for the extension.
and no via XDS metadata should this not be done. it belongs to the FHIR resource independent of the storage procedures and ERP context.

**Comment by eHealth-Suisse** [comment]
discussion 14.1.: ok
