### ISSUE TITLE
slicing vaccine codes -- CH VACD Immunization Profile (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#89]
ch.fhir.ig.ch-vacd#1.0.0 /StructureDefinition-ch-vacd-immunization.html

is the slicing correct? not sure if non-swiss immunizations can be captured (as discussed 22.9.2021)

Annatina Foppa, eHealth Suisse

**Comment by ralych** [comment]
Slicing validated with examples. vaccineCode can be from one of the valuesets declared in the profile
