### ISSUE TITLE
 Immunization Recommendation Request/Response as documents? (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#9]
ch.fhir.ig.ch-vacd#0.1.0 /profiles.html

Do Immunization Recommendation Request/Response have document character? In FHIR there would also be the possibility to use MessageHeader. Would it not be sufficient to just profile the necessary base resources for the Use case and drop the document profile? (e.g. a  CDS system based on FHIR API (cdshooks.org) will probably not use documents as input/output). 

Oliver Egger, ahdis

**Comment by ralych** [comment]
In discussion with eHS this is correct to do it a document. The mandat was to convert CDA to FHIR.
for cdshoocks, a bundle may be used i suppose. but deeper analyses has to be done.
from the side of the immunization experts, it is very important to have the complete set as defined for the cdss to give a recommendation as best as possible.

**Comment by ralych** [comment]
A bundle without composition could also be done.

**Comment by eHealth-Suisse** [comment]
open to discussion and to change our reasoning up to now

**Comment by eHealth-Suisse** [comment]
for now, we leave it as document. 
decision if document or bundle depends also on chosen architecture within EPR: how are immunization recommandations accessed, through which channel and tool? discussions ongoing.
ticket issues @oliveregger for information and potential objections
