### ISSUE TITLE
Allergies and Intolerance values for immunization (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#90]
ch.fhir.ig.ch-vacd#1.0.0 /ValueSet-ch-vacd-immunization-allergyintolerances-vs.html

Allergy profile according to CH:AllergyIntolerance

Annatina Foppa, eHealth Suisse

**Comment by ralych** [comment]
duplicates #82
