### ISSUE TITLE
Check usefulness of different documents (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#92]
ch.fhir.ig.ch-vacd#1.0.0 /

Are all five needed or could their number be reduced? Most important is that they comply with a future EPR integration, should be made dependent on the integration architecture

Annatina Foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment]
ok, follows the EPR vaccination concept
