### ISSUE TITLE
Definition ist falsch ch-vacd-ch-vaccination-plan-immunizations-vs (annatina foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#96]
ch.fhir.ig.ch-vacd#1.0.0 /ValueSet-ch-vacd-ch-vaccination-plan-immunizations-vs.html

vermutlich copy-paste-fehler, ist definition von den recommandation categories

annatina foppa, eHealth Suisse

**Comment by ralych** [comment]
ich meine das kommt von art-decor, doch leider kann ich das im moment nicht validieren, da art-decor nicht antwortet.

**Comment by eHealth-Suisse** [comment]
ok
