### ISSUE TITLE
Falscher Title gesetzt -- CH VACD Immunization Recommendation Response Composition Profile (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#97]
ch.fhir.ig.ch-vacd#1.0.0 /StructureDefinition-ch-vacd-composition-immunization-recommendation-response.html

Bei "title" sind die Werte von der Impfcheck-ANFRAGE drin, korrekt wäre für die RESPONSE jedoch (aus CDA-Specs kopiert): 
The document title MUST read:
▪ [en]: 'Immunization Recommendation'
▪ [de]: 'Impfempfehlung'
▪ [fr]: 'Recommandation vaccinale'
▪ [it]: 'Raccomandazione di vaccinazione'

Annatina Foppa, eHealth Suisse

**Comment by ralych** [comment]
![Screenshot from 2021-12-22 07-44-35](https://user-images.githubusercontent.com/75606442/147047802-6bc65c7c-2cd4-45ac-8f2f-77d991ff712b.png)
According to the Image, there are exactly this texts set as title...
